"""Full-chain P-Plan provenance (Phase C).

Asserts that a real run records the whole lineage — the upstream Order-Compiler
activities plus the runtime stage activities — as p-plan Activities and Entities,
and that the SOP-adherence check passes on a clean run and flags a deviation.
"""

from __future__ import annotations

import pathlib
import tempfile

from rdflib import RDF, URIRef

from compliance_engine import cli
from compliance_engine.order_compiler import compiler, cop
from compliance_engine.ontology.prefixes import CE, P_PLAN
from compliance_engine.pipeline.dataset import graph_for
from compliance_engine.traceability.provenance import check_sop_adherence


def _run_all_covered():
    ds, obligations = compiler.load_pipeline_dataset()
    cop_att = cop.attest_cop(ds, obligations, auto=True, now=cli.RUN_SEED_TS)
    order = compiler.compile_order(ds, obligations, cop_att, now=cli.RUN_SEED_TS)
    out = pathlib.Path(tempfile.mkdtemp(prefix="ce-prov-"))
    state = cli._do_run_factory(ds, order.iri, "all-covered", "fake", out)
    return ds, order, state


def _step(ds, name):
    exec_g = graph_for(ds, "plan_execution")
    step_uri = URIRef(f"{CE}step-{name}")
    return list(exec_g.subjects(P_PLAN.correspondsToStep, step_uri))


def test_upstream_and_runtime_activities_are_recorded():
    ds, _order, _state = _run_all_covered()
    # Upstream Order-Compiler steps.
    for name in ("ExtractObligations", "ResolveControls", "AttestCOP", "Gate1", "EmitOrder"):
        assert _step(ds, name), f"missing upstream activity for {name}"
    # Runtime Factory steps.
    for name in ("LoadOrder", "FetchByHash", "Plan", "PolicyCheck", "Apply",
                 "CollectEvidence", "Oracles"):
        assert _step(ds, name), f"missing runtime activity for {name}"


def test_variables_are_realized_by_entities():
    ds, _order, _state = _run_all_covered()
    exec_g = graph_for(ds, "plan_execution")
    realized = {str(v) for v in exec_g.objects(None, P_PLAN.correspondsToVariable)}
    for var in ("var-Contract", "var-Obligations", "var-RequiredControls", "var-COP",
                "var-Order", "var-ModuleHashes", "var-PlanHash", "var-Evidence",
                "var-OracleAssertions"):
        assert f"{CE}{var}" in realized, f"variable {var} has no realizing entity"


def test_full_chain_links_contract_to_order():
    ds, order, _state = _run_all_covered()
    exec_g = graph_for(ds, "plan_execution")
    # The contract entity is consumed by ExtractObligations.
    extract = _step(ds, "ExtractObligations")[0]
    contract_e = URIRef(f"{CE}entity/contract/{order.contract}")
    assert (extract, __import__("compliance_engine.ontology.prefixes",
            fromlist=["PROV"]).PROV.used, contract_e) in exec_g
    # The Order entity is generated by EmitOrder.
    emit = _step(ds, "EmitOrder")[0]
    order_e = URIRef(str(order.iri))
    from compliance_engine.ontology.prefixes import PROV
    assert (order_e, PROV.wasGeneratedBy, emit) in exec_g


def test_sop_adherence_passes_on_clean_run():
    ds, _order, _state = _run_all_covered()
    report = check_sop_adherence(ds)
    assert report.ok, report.summary()
    # The upstream + runtime steps all show as executed.
    assert "EmitOrder" in report.executed_steps
    assert "Oracles" in report.executed_steps


def test_sop_adherence_flags_an_orphan_activity():
    ds, _order, _state = _run_all_covered()
    # Inject an activity that corresponds to a step not in the plan.
    exec_g = graph_for(ds, "plan_execution")
    bogus_act = URIRef(f"{CE}exec/bogus/Nonsense")
    exec_g.add((bogus_act, RDF.type, P_PLAN.Activity))
    exec_g.add((bogus_act, P_PLAN.correspondsToStep, URIRef(f"{CE}step-Nonsense")))
    report = check_sop_adherence(ds)
    assert not report.ok
    assert report.orphan_activities
